module.exports = {
  body: {
    register: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'The user\'s name',
        },
        email: {
          type: 'string',
          description: 'The user\'s email',
        },
        password: {
          type: 'string',
          description: 'The password of the user',
        },
      },
    },
    login: {
      type: 'object',
      properties: {
        email: {
          type: 'string',
          description: 'The user\'s email',
        },
        password: {
          type: 'string',
          description: 'The password of the user',
        },
      },
    },
  },
  response: {
    200: {
      description: 'Successful login',
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'The user\'s name',
        },
        email: {
          type: 'string',
          description: 'The user\'s email',
        },
        token: {
          type: 'string',
          description: 'JWT token for the particular user, generated by the server',
        },
      },
    },
    201: {
      description: 'Successful registration',
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'The user\'s name',
        },
        email: {
          type: 'string',
          description: 'The user\'s email',
        },
        token: {
          type: 'string',
          description: 'JWT token for the particular user, generated by the server',
        },
      },
    },
    400: {
      type: 'object',
      properties: {
        message: {
          type: 'string',
          description: 'The message when user tries to submit wrong email or password'
        }
      }
    },
    500: {
      type: 'object',
      properties: {
        message: {
          type: 'string',
          description: 'The message when something happened with the server'
        }
      }
    }
  }
}
